### ISSUE TITLE
Unable to run the project locally

### ISSUE THREAD

**Issue by UlfurBen** [cowboy8625/rusty-rain#24]
I can access the directory but I can't find the commands. I only get -bash: cargo: command not found. The same with the other editing commands.

**Comment by cowboy8625** [comment]
The `cargo` command is a `rust` command.    You need to install rust with [rustup](https://rustup.rs).   If you just want to play around with the program there are release binary available too [here](https://github.com/cowboy8625/rusty-rain/releases).

**Comment by UlfurBen** [comment]
Thanks for the support!
